// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminkaV1.StorageDom.EfCore.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerExcDbContext))]
    [Migration("20250526174219_ExcConnectionIsActive")]
    partial class ExcConnectionIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectionsStorage.ExcConnectionForm", b =>
                {
                    b.Property<string>("ExcConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExcConnectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcConnectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcConnectionIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ExcConnectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcConnectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcConnectionXMeta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExcConnectionId");

                    b.ToTable("ExcConnections");
                });

            modelBuilder.Entity("ConnectionsStorage.ExcTable", b =>
                {
                    b.Property<string>("ExcTableId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExcConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcTableDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcTableFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcTablePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcTableXMeta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExcTableId");

                    b.ToTable("ExcTables");
                });
#pragma warning restore 612, 618
        }
    }
}
