using System;
using System.Threading.Tasks;

// TODO: this should be generated by T4
namespace DashboardCode.AdminkaV1.LoggingDom
{
    public interface ITraceServiceAsync
    {
        Task<Trace> GetTrace(Guid correlationToken);
    }
}
