using System;
using System.Collections.Generic;
using System.Threading.Tasks;

// TODO: this should be generated by T4
namespace DashboardCode.AdminkaV1.LoggingDom
{
    public interface ITraceServiceAsync
    {
        Task<List<VerboseRecord>> GetTraceAsync(Guid correlationToken);
    }
}
